console.log("");
console.log("patient-web-preview 只负责外部入口和 iframe 承载。");
console.log("");
console.log("先启动小程序源码的 Taro H5 预览：");
console.log("");
console.log("  cd ../patient-miniapp");
console.log("  npm run dev:h5");
console.log("");
console.log("再启动外部预览壳：");
console.log("");
console.log("  cd ../patient-web-preview");
console.log("  npm run dev");
console.log("");
console.log("小程序 H5 地址：");
console.log("");
console.log("  http://localhost:5175/");
console.log("");
console.log("外部预览壳地址：");
console.log("");
console.log("  http://localhost:5176/");
console.log("");
